services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testepx
      POSTGRES_PASSWORD: testepx
      POSTGRES_DB: testepx
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"    
      - "1025:1025"  
    networks:
      - app-network

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - app
      - redis
      - maildev
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
